[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
amm = "DHnQfvfUy7Yt92BxZxpj1G8UMWXyKyGGYHvUn2Lrb1xK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
